#include "gpio.h"

void GPIO_Initial( void )
{
  GPIO_Init( GPIOE, GPIO_PIN_7,GPIO_MODE_OUT_PP_LOW_SLOW );

  GPIO_Init( GPIOG, GPIO_PIN_0,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器1
  GPIO_Init( GPIOB, GPIO_PIN_0,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器2
  GPIO_Init( GPIOG, GPIO_PIN_1,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器3
  GPIO_Init( GPIOB, GPIO_PIN_1,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器4
  GPIO_Init( GPIOE, GPIO_PIN_0,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器5
  GPIO_Init( GPIOB, GPIO_PIN_2,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器6
  GPIO_Init( GPIOD, GPIO_PIN_0,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器7
  GPIO_Init( GPIOB, GPIO_PIN_3,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器8
  GPIO_Init( GPIOD, GPIO_PIN_2,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器9
  GPIO_Init( GPIOB, GPIO_PIN_6,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器A
  GPIO_Init( GPIOD, GPIO_PIN_3,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器B
  GPIO_Init( GPIOB, GPIO_PIN_7,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器C
  GPIO_Init( GPIOD, GPIO_PIN_4,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器D
  GPIO_Init( GPIOA, GPIO_PIN_4,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器E
  GPIO_Init( GPIOD, GPIO_PIN_7,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器F
  GPIO_Init( GPIOA, GPIO_PIN_5,GPIO_MODE_OUT_PP_HIGH_SLOW );//继电器0
}

